### ISSUE TITLE
Caught TypeError in DataLoader worker process 0 in DataLoader

### ISSUE THREAD

**Issue by 1359347500cwc** [hzxie/RMNet#18]
when I load Davis_dataset it always reports  "Caught TypeError in DataLoader worker process 0. " in test.py", line 78, "in test_net for idx, (video_name, n_objects, frames, masks, optical_flows) in enumerate(test_data_loader):"

**Comment by hzxie** [comment]
Please provide the full stacktrace.

**Comment by 1359347500cwc** [comment]
_Thanks for your reply!_  

**Here is the full stacktrace**

/home/cwc/RMNet/RMNet/utils/data_transforms.py:49: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  optical_flows = torch.from_numpy(np.array(optical_flows)).float().permute(0, 3, 1, 2)
/home/cwc/RMNet/RMNet/utils/data_transforms.py:49: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  optical_flows = torch.from_numpy(np.array(optical_flows)).float().permute(0, 3, 1, 2)
Traceback (most recent call last):
  File "runner.py", line 111, in <module>
    main()
  File "runner.py", line 96, in main
    test_net(cfg)
  File "/home/cwc/RMNet/RMNet/core/test.py", line 78, in test_net
    for idx, (video_name, n_objects, frames, masks, optical_flows) in enumerate(test_data_loader):
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cwc/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cwc/RMNet/RMNet/utils/data_loaders.py", line 76, in __getitem__
    frames, masks, opt_flows = self.transforms(frames, masks, opt_flows)
  File "/home/cwc/RMNet/RMNet/utils/data_transforms.py", line 36, in __call__
    frames, masks, optical_flows = transform(frames, masks, optical_flows)
  File "/home/cwc/RMNet/RMNet/utils/data_transforms.py", line 49, in __call__
    optical_flows = torch.from_numpy(np.array(optical_flows)).float().permute(0, 3, 1, 2)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

![image](https://user-images.githubusercontent.com/57097883/139566062-bafa540e-f77a-4056-9aed-e73d0f103217.png)

**here is the error point in line 49**
![image](https://user-images.githubusercontent.com/57097883/139566096-2ff53559-fc72-486d-abc9-5229a075cb67.png)

**So I add a dtype to change the type of numpy.object_  to 'float32' but it report a new error**
![image](https://user-images.githubusercontent.com/57097883/139566613-a45044cd-4440-4e04-b129-c415ff52aa5b.png)

**i also try to change the numpy to list then use the torch.LongTensor to convert it to tensor it report this error***
![image](https://user-images.githubusercontent.com/57097883/139566909-74c5cf96-177a-4813-8dcb-5ac99fea085b.png)

_I want to know whether it is the problem with my optical flow files?_

**Comment by Sand-Glass** [comment]
I have the same question
